In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

## Challenge: Make Your Network

Create a multi-layer perceptron neural network model to predict on a labeled dataset of your choosing. Compare this model to either a boosted tree or a random forest model and describe the relative tradeoffs between complexity and accuracy. Be sure to vary the hyperparameters of your MLP!

In [3]:
df = pd.read_csv("winequality-red.csv", delimiter=";")

In [4]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [5]:
# Binarize 'high quality' as 7 or greater
df["top_quality"] = np.where(df["quality"] >=7, 1, 0)

In [6]:
# Determine class balance
print("Class balance:", df["top_quality"].mean())

Class balance: 0.1357098186366479


In [7]:
#Specify inputs
X = df.iloc[:, :11]
Y = df["top_quality"]

## Neural Network

In [8]:
# Import model
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score

In [9]:
# Establish and fit with single, 100 perceptron layer 
mlp = MLPClassifier(hidden_layer_sizes=(100,))
mlp.fit(X,Y)

#Cross validate and get scores
cross_val_score(mlp, X, Y, cv=5)

/Users/yutakatsuyama/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/yutakatsuyama/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/yutakatsuyama/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/yutakatsuyama/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and th

array([0.87227414, 0.81931464, 0.89968652, 0.84326019, 0.86206897])

In [10]:
# Establish and fit with single, 100 perceptron layer 
mlp = MLPClassifier(hidden_layer_sizes=(1000,))
mlp.fit(X,Y)

#Cross validate and get scores
cross_val_score(mlp, X, Y, cv=5)

array([0.87227414, 0.81619938, 0.88714734, 0.84639498, 0.86833856])

In [11]:
# 100 perceptrons has slighty better performance and much faster run
# time.  Try adding second layer using 100 perceptrons.
mlp = MLPClassifier(hidden_layer_sizes=(100, 10))
mlp.fit(X,Y)

# Cross validate and get scores
cross_val_score(mlp, X, Y, cv=5)

# Second layer introduces less consistency in cross validation

/Users/yutakatsuyama/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


array([0.87850467, 0.83800623, 0.89968652, 0.85579937, 0.87147335])

In [13]:
#Adjust additional parameters using single, 100 perceptron
mlp = MLPClassifier(
    hidden_layer_sizes=(100,),
    activation="tanh",
    alpha = 10,
    learning_rate="adaptive"
)

mlp.fit(X,Y)

cross_val_score(mlp, X, Y, cv=5)

/Users/yutakatsuyama/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


array([0.86292835, 0.86292835, 0.86520376, 0.86520376, 0.86520376])

Tweaking hyperparameters, accuracy of 86% as good as I can get

## Random Forest

In [14]:
# Import model
from sklearn import ensemble
from sklearn.model_selection import GridSearchCV

In [19]:
# Initialize model
forest = ensemble.RandomForestClassifier(
    max_features='sqrt',
)

# Set hyperparameter
max_depth = dict(max_depth = np.arange(1,10,1))

# Set up grid search for forest depth
grid = GridSearchCV(forest, max_depth, cv=5)

# Fit and get results
results = grid.fit(X, Y)
results.best_estimator_.get_params()['max_depth']

/Users/yutakatsuyama/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Users/yutakatsuyama/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Users/yutakatsuyama/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Users/yutakatsuyama/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Users/yutak

/Users/yutakatsuyama/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Users/yutakatsuyama/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Users/yutakatsuyama/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Users/yutakatsuyama/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Users/yutak

4

In [20]:
forest = ensemble.RandomForestClassifier(
    max_features="sqrt",
    max_depth=4)

cross_val_score(forest, X, Y, cv=5)

/Users/yutakatsuyama/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Users/yutakatsuyama/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Users/yutakatsuyama/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Users/yutakatsuyama/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Users/yutak

array([0.86604361, 0.86604361, 0.89655172, 0.88087774, 0.89341693])

In [22]:
forest.fit(X,Y)

forest_features = pd.DataFrame()
forest_features["importance"] = forest.feature_importances_
forest_features["feature"] = X.columns

forest_features.sort_values("importance", ascending=False).head()

importance           feature
10    0.262771           alcohol
9     0.180449         sulphates
1     0.153452  volatile acidity
7     0.113922           density
2     0.065617       citric acid

## Model comparison

Roughly equal performance between both models in this instance.

Neural Network:
    - More consistant performance across folds
    - More computationally demanding
    - No insights into feature importance
    
Random Forest:
    - Slightly less consistent across folds
    - Faster to run
    - gives feature importances